version: "3.7"
volumes:
  connector_db_data: null
  connector_logs: null
  patientlist_db_data: null
  patientlist_logs: null
  idmanager_logs: null
  store_db_data: null
  store_logs: null
secrets:
  mainzelliste.docker.conf:
    file: ./internal-configuration/mainzelliste.conf
  magicpl.docker.xml:
    file: ./internal-configuration/magicpl.xml
  dktk_bridgehead_info.docker.xml:
    file: ./internal-configuration/bridgehead-common.xml
  centralSearchPublicKey:
    file: ./internal-configuration/centralSearchPublicKey.der
  proxy.docker.xml:
    file: ./internal-configuration/proxy.xml

services:
  connector:
    container_name: bridgehead_c4_connector
    image: "samply/share-client:c4-7"
    environment:
      SITE: ${SITE}
      SITEID: ${SITEID}
      CENTRAL_SEARCH: ${CCP_CENTRALSEARCH_URL}
      DECENTRAL_SEARCH: ${CCP_DECENTRALSEARCH_URL}
      MDR_URL: ${CCP_MDR_URL}
      MONITOR_URL: ${CCP_MONITOR_URL}
      SHARE_URL: "${PROTOCOL}://${HOST}:${PORT}"
      ID_MANAGER_URL: ${ID_MANAGER_URL}
      PROJECTPSEUDONYMISATION_URL: ${PROJECTPSEUDONYMISATION_URL}
      PATIENTLIST_URL: ${PATIENTLIST_URL}
      STORE_URL: ${LDM_URL}
      POSTGRES_HOST: ${CONNECTOR_DB_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${CONNECTOR_POSTGRES_DB}
      POSTGRES_USER: ${CONNECTOR_POSTGRES_USER}
      POSTGRES_PASS: ${C4_CONNECTOR_POSTGRES_PASSWORD}
      DEPLOYMENT_CONTEXT: ${COMPOSE_PROJECT_NAME}-connector
      HTTP_PROXY_URL: ${HTTP_PROXY_URL}
      HTTP_PROXY_USERNAME: ${HTTP_PROXY_USERNAME}
      HTTP_PROXY_PASSWORD: ${HTTP_PROXY_PASSWORD}
      HTTPS_PROXY_URL: ${HTTPS_PROXY_URL}
      HTTPS_PROXY_USERNAME: ${HTTPS_PROXY_USERNAME}
      HTTPS_PROXY_PASSWORD: ${HTTPS_PROXY_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - "connector_logs:/usr/local/tomcat/logs"
    depends_on:
      - connector_db
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${HOST}:${HOSTIP}"

  connector_db:
    container_name: bridgehead_connector_db
    image: postgres:10.17
    environment:
      POSTGRES_DB: ${CONNECTOR_POSTGRES_DB}
      POSTGRES_USER: ${CONNECTOR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${C4_CONNECTOR_POSTGRES_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - "connector_db_data:/var/lib/postgresql/data"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${HOST}:${HOSTIP}"

  ## ID-Management
  idmanager:
    container_name: bridgehead_idmanager
    image: docker.verbis.dkfz.de/pseudonymisierung/magicpl:release-0.2.0
    environment:
      MAGICPL_MAINZELLISTE_CENTRAL_URL: ${CCP_PATIENTLIST_URL}
      MAGICPL_CENTRAL_URL: ${CCP_CONTROLLNUMBERGENERATOR_URL}
      MAGICPL_SITE: ${SITEID}
      MAGICPL_LOG_LEVEL: info
      GLOBAL_ID: DKTK

      TZ: Europe/Berlin
    volumes:
      - "idmanager_logs:/usr/local/tomcat/logs"
    secrets:
      - magicpl.docker.xml
      - dktk_bridgehead_info.docker.xml
      - proxy.docker.xml

  store:
    container_name: bridgehead_store
    image: docker.verbis.dkfz.de/ccp/samply.store:release-5.1.2
    environment:
      MDR_URL: ${CCP_MDR_URL}
      MDR_NAMESPACE: adt,dktk,marker
      MDR_VALIDATION: "false"
      POSTGRES_HOST: store_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: samplystore
      POSTGRES_USER: samplystore
      POSTGRES_PASSWORD: ${C4_SAMPLY_STORE_PASS}
      TZ: Europe/Berlin
    volumes:
      - "store_logs:/usr/local/tomcat/logs"
    depends_on:
      - store_db
    restart: always

  store_db:
    container_name: bridgehead_store_db
    image: postgres:10.17
    command: postgres -c datestyle='iso, dmy'
    environment:
      POSTGRES_HOST: store_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: samplystore
      POSTGRES_USER: samplystore
      POSTGRES_PASSWORD: ${C4_SAMPLY_STORE_PASS}
      TZ: Europe/Berlin
    volumes:
      - "store_db_data:/var/lib/postgresql/data"
    restart: always
