version: "3.7"
volumes:
  connector_db_data:
  connector_logs:
  patientlist_db_data:
  patientlist_logs:
  idmanager_logs:
  store_db_data:
  store_logs:
secrets:
  mainzelliste.docker.conf:
    file: ../internal-configuration/mainzelliste.conf
  magicpl.docker.xml:
    file: ../internal-configuration/magicpl.xml
  dktk_bridgehead_info.docker.xml:
    file: ../internal-configuration/bridgehead-common.xml
  centralSearchPublicKey:
    file: ../internal-configuration/centralSearchPublicKey.der
  proxy.docker.xml:
    file: ../internal-configuration/proxy.xml

services:
  connector:
    container_name: bridgehead_dktk_connector
    image: "samply/share-client:dktk-7"
    environment:
      STORE_URL: ${STORE_URL}
      POSTGRES_HOST: ${CONNECTOR_DB_HOST}
      POSTGRES_PASS: ${CONNECTOR_POSTGRES_PASS}
    volumes:
      - "connector_logs:/usr/local/tomcat/logs"
    depends_on:
      - connector_db
    ports:
      - "8080:8080"
    restart: always
    env_file:
    ###TODO: Move into Image
      - internal.env
    networks:
      - "samply"
      - "connector-db"

  connector_db:
    container_name: bridgehead_dktk_connector_db
    image: postgres:10.17
    environment:
      POSTGRES_HOST: ${CONNECTOR_DB_HOST}
      POSTGRES_PASSWORD: ${CONNECTOR_POSTGRES_PASS}
    volumes:
      - "connector_db_data:/var/lib/postgresql/data"
    restart: always
    env_file:
    ###TODO: Move into Image
      - internal.env
    networks:
      - "connector-db"


  idmanager:
    container_name: bridgehead_dktk_idmanager
    image: docker.verbis.dkfz.de/pseudonymisierung/magicpl:release-0.2.0
    environment:
      MAGICPL_MAINZELLISTE_URL: ${MAGICPL_MAINZELLISTE_URL}
      MAGICPL_MAINZELLISTE_API_KEY: ${MAGICPL_MAINZELLISTE_API_KEY}
      MAGICPL_API_KEY: ${MAGICPL_API_KEY}
      MAGICPL_API_KEY_CONNECTOR: ${MAGICPL_API_KEY_CONNECTOR}
      MAGICPL_PASSPHRASE: ${MAGICPL_PASSPHRASE}
      MAGICPL_MAINZELLISTE_CENTRAL_URL: ${MAGICPL_MAINZELLISTE_CENTRAL_URL}
      MAGICPL_MAINZELLISTE_CENTRAL_API_KEY: ${MAGICPL_MAINZELLISTE_CENTRAL_API_KEY}
      MAGICPL_CENTRAL_URL: ${MAGICPL_CENTRAL_URL}
      MAGICPL_CENTRAL_API_KEY: ${MAGICPL_CENTRAL_API_KEY}
      MAGICPL_OIDC_PROVIDER: ${MAGICPL_OIDC_PROVIDER}
      MAGICPL_OIDC_CLIENT_ID: ${MAGICPL_OIDC_CLIENT_ID}
      MAGICPL_OIDC_CLIENT_SECRET: ${MAGICPL_OIDC_CLIENT_SECRET}

      TZ: Europe/Berlin
    volumes:
      - "idmanager_logs:/usr/local/tomcat/logs"
    secrets:
      - magicpl.docker.xml
      - dktk_bridgehead_info.docker.xml
      - proxy.docker.xml
    depends_on:
      - patientlist
    env_file:
    ###TODO: Move into Image
      - internal.env
    ports:
      - "8085:8080"
    networks:
      - "samply"

  patientlist:
    container_name: bridgehead_dktk_patientlist
    image: medicalinformatics/mainzelliste:develop
    environment:
      ML_DB_HOST: bridgehead_dktk_patientlist_db
      ML_DB_PASS: ${ML_DB_PASS}
      ML_API_KEY: ${ML_API_KEY}
    env_file:
      - ../site-config/patientlist.env
      - internal.env
    volumes:
      - "patientlist_logs:/usr/local/tomcat/logs"
    secrets:
      - mainzelliste.docker.conf
      - centralSearchPublicKey
    depends_on:
      - patientlist_db
    ports:
      - "8086:8080"
    networks:
      - "samply"

  patientlist_db:
    container_name: bridgehead_dktk_patientlist_db
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: ${ML_DB_PASS}
    volumes:
      - "patientlist_db_data:/var/lib/postgresql/data"
    env_file:
    ###TODO: Move into Image
      - internal.env
    networks:
      - "samply"
      
networks:
  samply:
    driver: "bridge"
  connector-db:
    driver: "bridge"