version: "3.7"

services:
  beam-proxy:
    environment:
      APP_2_ID: dnpm
      APP_2_KEY: ${DNPM_BEAM_SECRET_SHORT}

  dnpm-beam-connect:
    depends_on: [ beam-proxy ]
    image: samply/beam-connect:sites-without-auth
    environment:
      PROXY_URL: http://beam-proxy:8081
      PROXY_APIKEY: ${DNPM_BEAM_SECRET_SHORT}
      APP_ID: dnpm.${PROXY_ID}
      DISCOVERY_URL: ${DNPM_DISCOVERY_URL}
      LOCAL_TARGETS_FILE: /run/secrets/connect_targets.json
      HTTP_PROXY: http://forward_proxy:3128
      HTTPS_PROXY: http://forward_proxy:3128
      NO_PROXY: beam-proxy,dnpm-backend
      RUST_LOG: ${RUST_LOG:-info}
    secrets:
      - connect_targets.json
    ports:
      - 8062:8062

secrets:
  connect_targets.json:
    file: /etc/bridgehead/dnpm/local_targets.json
