version: '3.4'

volumes:
  gbn-connector-logs:
  gbn-connector-db-data:
  gbn-store-db-data:

services:
  traefik:
    container_name: traefik
    image: traefik:2.4
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  landing:
    container_name: landingpage
    image: nginx:stable
    volumes:
      - ../landing/:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=PathPrefix(`/`)"
      - "traefik.http.services.landing.loadbalancer.server.port=80"

  gbn-connector:
    image: "samply/share-client:gbn-feature-environmentPreconfigurationTorben"
    environment:
      POSTGRES_HOST: "gbn-connector-db"
      ID_MANAGER_APIKEY: ${MAGICPL_API_KEY_CONNECTOR}
      POSTGRES_PASSWORD: ${CONNECTOR_POSTGRES_PASS}
      HTTP_PROXY_USER: ${HTTP_PROXY_USER}
      HTTP_PROXY_PASSWORD: ${HTTP_PROXY_PASSWORD}
      HTTPS_PROXY_USER: ${HTTPS_PROXY_USER}
      HTTPS_PROXY_PASSWORD: ${HTTPS_PROXY_PASSWORD}
      LDM_URL: "${PROTOCOL}://${HOST}:${PORT}/fhir"
    env_file:
      - ../site-config/gbn.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${HOST}:${HOSTIP}"
    volumes:
      - "gbn-connector-logs:/usr/local/tomcat/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gbn_connector.rule=PathPrefix(`/gbn-connector`)"
      - "traefik.http.services.gbn_connector.loadbalancer.server.port=8080"
    depends_on:
      - "gbn-connector-db"
    restart: "always"

  gbn-connector-db:
    image: "postgres:10.17"
    environment:
      POSTGRES_DB: "samply.connector"
      POSTGRES_USER: "samply"
      POSTGRES_PASSWORD: ${CONNECTOR_POSTGRES_PASS}
    volumes:
      - "gbn-connector-db-data:/var/lib/postgresql/data"
    restart: "always"

  gbn-store:
    image: "samply/blaze:0.15"
    environment:
      BASE_URL: "${PROTOCOL}://${HOST}:${PORT}"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
    env_file:
      - ../site-config/gbn.env
    volumes:
      - "gbn-store-db-data:/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.test-auth.basicauth.users=user:$$apr1$$RjhTX8\
        ji$$3ToBWBch1K4RBnvp86TuH/"
      - "traefik.http.routers.blaze_gbn.rule=PathPrefix(`/gbn-localdatamanagement`)"
      - "traefik.http.middlewares.gbn_b_strip.stripprefix.prefixes=/gbn-localdatamanagement"
      - "traefik.http.services.blaze_gbn.loadbalancer.server.port=8080"
      - "traefik.http.routers.blaze_gbn.middlewares=gbn_b_strip,test-auth"
    restart: "always"
