version: '3.4'
networks:
  samply:
    driver: "bridge"
  connector-db:
    driver: "bridge"

volumes:
  store-db-data:
    name: "store-db-data"
  connector-db-data:
    name: "connector-db-data"

services:
  store:
    container_name: "bridgehead_gbn_blaze_store"
    image: "samply/blaze:0.15"
    environment:
      BASE_URL: "http://bridgehead_gbn_blaze_store:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
    networks:
      - "samply"
    volumes:
      - "store-db-data:/app/data"
    ports:
      - "8080:8080"
    restart: "always"

  connector:
    container_name: "bridgehead_gbn_connector"
    image: "samply/share-client:gbn-7"
    environment:
      POSTGRES_HOST: "bridgehead_gbn_connector_db"
      POSTGRES_PASS: ${CONNECTOR_POSTGRES_PASS}
      POSTGRES_PORT: 5432
      STORE_URL: "http://bridgehead_gbn_blaze_store:8080/fhir"
    env_file:
    ###TODO: Move into Image
      - internal.env
    networks:
      - "samply"
      - "connector-db"
    ports:
      - "8082:8080"
    depends_on:
      - "connector-db"
    restart: "always"

  connector-db:
    container_name: "bridgehead_gbn_connector_db"
    image: "postgres:10.17"
    environment:
      POSTGRES_PASSWORD: ${CONNECTOR_POSTGRES_PASS}
      POSTGRES_PORT: 5432
    networks:
      - "connector-db"
    volumes:
      - "connector-db-data:/var/lib/postgresql/data"
    restart: "always"
    env_file:
    ###TODO: Move into Image
      - internal.env