version: "3.7"

services:
  adt2fhir-rest:
    container_name: bridgehead-adt2fhir-rest
    image: docker.verbis.dkfz.de/ccp/adt2fhir-rest:main
    environment:
      IDTYPE: BK_${IDMANAGEMENT_FRIENDLY_ID}_L-ID
      MAINZELLISTE_APIKEY: ${IDMANAGER_LOCAL_PATIENTLIST_APIKEY}
      SALT: ${LOCAL_SALT}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adt2fhir-rest.rule=PathPrefix(`/adt2fhir-rest`)"
      - "traefik.http.middlewares.adt2fhir-rest_strip.stripprefix.prefixes=/adt2fhir-rest"
      - "traefik.http.services.adt2fhir-rest.loadbalancer.server.port=8080"
      - "traefik.http.routers.adt2fhir-rest.tls=true"
      - "traefik.http.routers.adt2fhir-rest.middlewares=adt2fhir-rest_strip,auth"