version: '3.7'

services:
  cbioportal:
    image: docker.verbis.dkfz.de/ccp/dktk-cbioportal:latest
    container_name: bridgehead-cbioportal
    environment:
      DB_PASSWORD: ${CBIOPORTAL_DB_PASSWORD}
      HTTP_RELATIVE_PATH: "/cbioportal"
      UPLOAD_HTTP_RELATIVE_PATH: "/cbioportal-upload"
    depends_on:
      - cbioportal-database
      - cbioportal-session
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cbioportal.rule=PathPrefix(`/cbioportal`)"
      - "traefik.http.routers.cbioportal.service=cbioportal"
      - "traefik.http.services.cbioportal.loadbalancer.server.port=8080"
      - "traefik.http.routers.cbioportal.tls=true"
      - "traefik.http.routers.cbioportal-upload.rule=PathPrefix(`/cbioportal-upload`)"    
      - "traefik.http.routers.cbioportal-upload.service=cbioportal-upload"
      - "traefik.http.routers.cbioportal-upload.tls=true"
      - "traefik.http.services.cbioportal-upload.loadbalancer.server.port=8001" 
      
      

  cbioportal-database:
    image: docker.verbis.dkfz.de/ccp/dktk-cbioportal-database:latest
    container_name: bridgehead-cbioportal-database
    environment:
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio_user
      MYSQL_PASSWORD: ${CBIOPORTAL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${CBIOPORTAL_DB_ROOT_PASSWORD}
    volumes:
      - /var/cache/bridgehead/ccp/cbioportal_db_data:/var/lib/mysql

  cbioportal-session:
    image: cbioportal/session-service:0.6.1
    container_name: bridgehead-cbioportal-session
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal-session-database:27017/session-service
    depends_on:
      - cbioportal-session-database

  cbioportal-session-database:
    image: mongo:4.2
    container_name: bridgehead-cbioportal-session-database
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - /var/cache/bridgehead/ccp/cbioportal_session_db_data:/data/db
      