version: "3.7"

services:
  traefik:
    container_name: bridgehead_traefik
    image: traefik:2.4
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ../certs:/tools/certs
      - ../tools/traefik/:/configuration/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../auth/:/auth
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  landing:
    container_name: bridgehead_landingpage
    image: nginx:stable
    volumes:
      - ../landing/:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=PathPrefix(`/`)"
      - "traefik.http.services.landing.loadbalancer.server.port=80"
      - "traefik.http.routers.landing.tls=true"

  blaze:
    image: "samply/blaze:0.15"
    container_name: bridgehead_dktk_blaze
    environment:
      BASE_URL: "http://blaze:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      LOG_LEVEL: "debug"
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    volumes:
    - "blaze-data:/app/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blaze_dktk.rule=PathPrefix(`/dktk-localdatamanagement`)"
      - "traefik.http.middlewares.dktk_b_strip.stripprefix.prefixes=/dktk-localdatamanagement"
      - "traefik.http.services.blaze_dktk.loadbalancer.server.port=8080"
      - "traefik.http.routers.blaze_dktk.middlewares=dktk_b_strip"
  

volumes:
  blaze-data:
